import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavbarDashboardComponent from "@/components/dashboard-anggota/navbar";
import "./../globals.css";
import TopbarComponent from "@/components/dashboard-anggota/topbar";
import { Slide, ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-page bg-[#f8f8f8] min-h-screen">
          <div className="flex min-h-screen">
            <div className="w-[18%] fixed h-full sw-1/5 h-full bg-white min-h-screen">
              <NavbarDashboardComponent />
            </div>
            <div className="ml-[18%] w-2/3 h-full min-h-screen w-full">
              <TopbarComponent />
              <div className="m-4 p-4 bg-white rounded-xl">
                {children}
                <ToastContainer
                  transition={Slide}
                  closeButton={false}
                  hideProgressBar={true}
                />
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
