import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.css";
import { Slide, ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthenticationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ToastContainer
          transition={Slide}
          closeButton={false}
          hideProgressBar={true}
        />
      </body>
    </html>
  );
}
